//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int ID { get; set; }
        public int animal_id { get; set; }
        public int doctor_id { get; set; }
        public System.DateTime date { get; set; }
        public string comment { get; set; }
        public bool isDelete { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
